apiVersion: batch/v1
kind: Job
metadata:
  name: parking-occupancy-compute-test
  namespace: prod
spec:
  template:
    metadata:
      labels:
        job-name: parking-occupancy-compute-test
    spec:
      containers:
      - args:
        - occupancy.py
        - -h http://crate-crate:4200
        - -r True
        image: orchestracities/parking-occupancy:latest
        imagePullPolicy: Always
        name: parking-occupancy
      restartPolicy: OnFailure
